### ISSUE TITLE
Current trigger running on old DB tables

### ISSUE THREAD

**Issue by tomage** [jyveapp/django-pgtrigger#7]
So, @wesleykendall - I recently came across a pretty nasty problem. Although, fortunately, it's unlikely one will really see it happen in production.

The problem happened when we were running migrations on a somewhat old database. Since that database, many models had been added and updated. Even removed. In this case, there was a new NOT NULL field on a model.

As it happens, one of the migration was a data migration that hadn't been run was on that model, but at that point in time, the field hadn't been added.

So the field was there in the code, but not in the database. But, because we had run partial migrations, on another app, we had installed all the latest and greatest triggers.

One such trigger was via the `pghistory` library, to track history on that model.

What happened next is this:

The data migration did some change to one row from that table. Immediately, the `pghistory` based trigger decided to create a historical record of the change in it's table - but alas - that table was based on the latest version of the model, which had a NOT NULL field, but there was no value present, since that field didn't exist yet on the main model.

The solution was to disable triggers before running all the migrations (via `pgtriggers.uninstall()`).

Of course, this probably only happens for this scenario, where the DB is severely out of date. And no doubt, in those scenarios, it's probably fine to disable triggers before running migrations.

So I don't see this as a severe problem in any way. But perhaps in future versions, there might be some ways to handle this. Or, at any rate, I figured to document the "issue" here, in case someone came across the same problem later on.

It's also likely that with named triggers, it'll be easier to avoid these scenarios. For example, I could have added something like `with pgtrigger.disable('sync_model_x'):` in the data migration, if I thought it likely to cause this issue.

But most likely, this is not a scenario that will happen often (if at all) in realistic production scenarios.

I thought of posting this in `pghistory` library, but this might easily also affect other cases. For example, if I had written a trigger that mentioned the new field, but the new field didn't exist when the migration ran. Would end up with a similar error, I'm guessing.

**Comment by wesleykendall** [comment]
@tomage yea that's an interesting scenario I didn't expect.

I believe that situations like these will be easier to deal with once there are appropriate management commands in place for individual triggers.

With that in mind, it might also be good to find a way to only install triggers for an app when that specific app is migrated. And only do a full trigger install whenever all migrations are executed. I.e. `manage.py migration my_app` will only do trigger installations for `my_app` but `manage.py migrate` will install all triggers for every app. Not totally sure how easy it is to do this though. Would that have helped avoid this particular issue?

If Django fires the post_migrate signal for every app, regardless of if they have migrations, it might be pretty easy to do that suggestion. We'd still need to do one big prune command at the end to clean up stale triggers though.

**Comment by tomage** [comment]
Not sure if per-app installs would have helped. Someone could have migrated until `myapp.0007`, because `myapp.0008` was something that needed to be run separately. But in doing 0007, it installed all the current triggers, potentially breaking the run of 0008.

But.. I honestly don't think this is such a big issue. Probably is mainly an issue when ppl have multiple parallel copies of a DB that they run in parallel to the main one, and if the update those on a less frequent basis than that of the main production one.

For my case - it was pretty obvious what was going on (well.. obvious if one knows about most of the triggers involved :) ), and after that it was trivial to disable triggers, and re-enable after migration was run.

**Comment by tomage** [comment]
Phew! Just had a pretty bad version of this happen in production.

Here's the situation (simplified):

Let's say we have these migrations we have to run for a release:

items.0005 (Backfill of some field)
jobs.0020 (Adds a new field `price` to a `Job` model)

And let's say that in the release, we just added a pgtrigger that fills in the `Job.price` field based on other field, let's say `cost`.

If someone were to run `items.0005` first (i.e. `./manage.py migrate items 0005`, in the post-migrate hooks, we'll now install the new pgtrigger.

This caused inserts into the DB table for `Job` model to fail instantly, because now there's a DB trigger that tries to keep the non-existetent `price` column in sync with the `cost` column.

But it doesn't exist until `jobs.0020` has been run.

Well.. The temporary fix was to disable that trigger (took a bit of wrangling), then run `jobs.0020` and let post-migrate hook re-install the trigger.

Regarding a solution.. not sure. Kinda starting to feel like to me that triggers should be installed inside migrations - explicitly. That way, I'd either have to modify `jobs.0020` to install that new particular trigger after the `AddField` operation, or even create a data migrations (`jobs.0021`) in which I'd install that trigger.

Perhaps this would play well with moving over to named triggers? What do you think @wesleykendall ?

Anyway.. Until we've found a proper fix for the issue, we'll be doing releases with extra care w.r.t. changes made to pgtriggers used in our codebase. Not a big deal - but will def. be an important step for us to keep near zero-downtime deployments :)

**Comment by tomage** [comment]
With the additions made in https://github.com/jyveapp/django-pgtrigger/pull/11, it has pretty much solved this problem - tho in practice, one might easily encounter this from time to time. But with the new utilities, it's easier to disable individual triggers and re-enable again, either in one's migrations, or for example in the shell, when one is running more nuanced migration execution.
